Vagrant.configure(2) do |config|
  config.vm.box = "jmeth-centos7-qemu"
  config.vm.box_url = "file://../build/jmeth-centos7.box"
  config.vm.hostname = "vagrant-kvm-test"
  config.vm.provider :libvirt do |libvirt|
    libvirt.nested = true
    libvirt.driver = "kvm"
  end
end
